language: node_js

sudo: true

services:
  - elasticsearch
  - redis-server
  - postgresql

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

before_install:
  - 'curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.3.4.deb && sudo dpkg -i --force-confnew elasticsearch-2.3.4.deb && sudo service elasticsearch restart'

before_script:
  - sleep 10
  - "psql -c 'create database inbify_test;' -U postgres"
  - 'echo "script.inline: true" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - 'sudo service elasticsearch restart'

script:
  - "npm test"
