language: node_js

sudo: true

services:
  - elasticsearch
  - redis-server
  - postgresql

osx_image: xcode7.3

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

before_script:
  - sleep 10
  - "psql -c 'create database inbify_test;' -U postgres"
  - 'echo "script.inline: true" | sudo tee -a /etc/elasticsearch/elasticsearch.yml'
  - 'sudo service elasticsearch restart'
  - sleep 10

script:
  - "npm test"