language: node_js

sudo: false

services:
  - elasticsearch
  - redis-server
  - postgresql

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

env:
  - TRAVIS=travis CXX=g++-4.8

before_script:
  - sleep 10
  - "psql -c 'create database inbify_test;' -U postgres"
  - echo "script.inline: true" >> /etc/elasticsearch/config/elasticsearch.yml
  - echo $PATH

script:
  - "npm test"
